import type { ApiKeyRecord, AuditEvent, ExchangeConnection, RiskRules, TradeLimits, UserPreferences, UserProfile, WalletConnection } from '../types/trading';

export const exchanges: ExchangeConnection[] = [
  {
    connectorType: 'api-key',
    feeTier: 'Spot/perp fees by account tier',
    id: 'binance',
    idealFor: 'Liquidity, USDT pairs and live market data',
    marketType: 'spot',
    name: 'Binance',
    networks: ['Spot', 'USDT Perps'],
    permissions: [],
    routingNote: 'Primary live executor when THOON_LIVE_EXCHANGE_PROVIDER=binance.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot/perp fees by account tier',
    id: 'bybit',
    idealFor: 'Perpetuals and public REST candles',
    marketType: 'perpetual',
    name: 'Bybit',
    networks: ['Spot', 'USDT Perps'],
    permissions: [],
    routingNote: 'Public candle source wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot/perp fees by account tier',
    id: 'okx',
    idealFor: 'Multi-market routing and derivatives',
    marketType: 'perpetual',
    name: 'OKX',
    networks: ['Spot', 'USDT Perps'],
    permissions: [],
    routingNote: 'Public candle source wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot/perp fees by account tier',
    id: 'bitget',
    idealFor: 'Perpetuals and copy-trading style venues',
    marketType: 'perpetual',
    name: 'Bitget',
    networks: ['Spot', 'USDT Perps'],
    permissions: [],
    routingNote: 'Public candle source wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot fees by tier',
    id: 'kraken',
    idealFor: 'Spot execution and fiat-friendly crypto routing',
    marketType: 'spot',
    name: 'Kraken',
    networks: ['Spot'],
    permissions: [],
    routingNote: 'Spot public candles wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot fees by tier',
    id: 'kucoin',
    idealFor: 'Altcoin spot markets',
    marketType: 'spot',
    name: 'KuCoin',
    networks: ['Spot'],
    permissions: [],
    routingNote: 'Spot public candles wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'api-key',
    feeTier: 'Spot fees by tier',
    id: 'coinbase-advanced',
    idealFor: 'USD spot liquidity',
    marketType: 'spot',
    name: 'Coinbase Advanced',
    networks: ['Spot'],
    permissions: [],
    routingNote: 'Spot public candles wired; live execution remains gated.',
    status: 'available',
    venueType: 'cex',
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Maker/taker tiers',
    id: 'dydx',
    idealFor: 'Perpetuals via wallet-based execution',
    marketType: 'perpetual',
    name: 'dYdX',
    networks: ['dYdX Chain', 'Cosmos wallet'],
    permissions: [],
    routingNote: 'Official dYdX signer is implemented server-side and stays locked until permissioned key readiness passes.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Maker/taker tiers',
    id: 'hyperliquid',
    idealFor: 'Fast perpetual trading from a decentralized wallet',
    marketType: 'perpetual',
    name: 'Hyperliquid',
    networks: ['HyperCore', 'HyperEVM'],
    permissions: [],
    routingNote: 'Official Hyperliquid SDK signer is implemented server-side and stays locked until API wallet readiness passes.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: '0.01% / 0.05% / 0.25% / 1%',
    id: 'pancakeswap',
    idealFor: 'BNB Chain, Base, Arbitrum, Solana, opBNB',
    marketType: 'swap',
    name: 'PancakeSwap',
    networks: ['BNB Chain', 'Base', 'Arbitrum', 'Solana', 'opBNB'],
    permissions: [],
    routingNote: 'Low-fee DEX route for non-Ethereum-mainnet swaps.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Around 0.04%',
    id: 'curve',
    idealFor: 'Stablecoins: USDC, USDT, DAI, crvUSD, FRAX',
    marketType: 'stable-swap',
    name: 'Curve Finance',
    networks: ['Ethereum', 'Arbitrum', 'Optimism', 'Base', 'Polygon'],
    permissions: [],
    routingNote: 'Stable swap route for low slippage baskets.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: '0.01% / 0.05% / 0.3% / 1%',
    id: 'uniswap',
    idealFor: 'High-volume liquid tokens',
    marketType: 'swap',
    name: 'Uniswap v3/v4',
    networks: ['Base', 'Arbitrum', 'Optimism', 'Polygon', 'Unichain', 'Ethereum'],
    permissions: [],
    routingNote: 'Prefer L2 networks when Ethereum mainnet gas is expensive.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'aggregator',
    feeTier: 'Variable',
    id: '1inch',
    idealFor: 'Finding the best price across multiple DEX routes',
    marketType: 'aggregator',
    name: '1inch',
    networks: ['Ethereum', 'BNB Chain', 'Base', 'Arbitrum', 'Optimism', 'Polygon'],
    permissions: [],
    routingNote: 'Aggregator route for reducing fees and slippage.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'aggregator',
    feeTier: 'Variable',
    id: 'matcha-0x',
    idealFor: 'Simple wallet swaps with route comparison',
    marketType: 'aggregator',
    name: 'Matcha / 0x',
    networks: ['Ethereum', 'Base', 'Arbitrum', 'Optimism', 'Polygon'],
    permissions: [],
    routingNote: 'Clean aggregator route for direct wallet swaps.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'aggregator',
    feeTier: 'Variable',
    id: 'cow-swap',
    idealFor: 'Large swaps on Ethereum and Gnosis',
    marketType: 'aggregator',
    name: 'CoW Swap',
    networks: ['Ethereum', 'Gnosis'],
    permissions: [],
    routingNote: 'Batch auction route intended to reduce hidden MEV and bad routing costs.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Low DEX fees + low Solana gas',
    id: 'raydium',
    idealFor: 'Solana swaps',
    marketType: 'swap',
    name: 'Raydium',
    networks: ['Solana'],
    permissions: [],
    routingNote: 'Fast Solana swap venue for Phantom or Solflare flows.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Low DEX fees + low Solana gas',
    id: 'orca',
    idealFor: 'Simple Solana swaps from Phantom or Solflare',
    marketType: 'swap',
    name: 'Orca',
    networks: ['Solana'],
    permissions: [],
    routingNote: 'Simple Solana wallet swap route.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Often competitive',
    id: 'aerodrome',
    idealFor: 'Base tokens and stablecoins',
    marketType: 'swap',
    name: 'Aerodrome',
    networks: ['Base'],
    permissions: [],
    routingNote: 'Core Base liquidity route.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
  {
    connectorType: 'wallet',
    feeTier: 'Often competitive',
    id: 'velodrome',
    idealFor: 'Optimism ecosystem tokens',
    marketType: 'swap',
    name: 'Velodrome',
    networks: ['Optimism'],
    permissions: [],
    routingNote: 'Core Optimism liquidity route.',
    status: 'available',
    venueType: 'dex',
    walletRequired: true,
    withdrawalsEnabled: false,
  },
];

export const wallets: WalletConnection[] = [];

export const apiKeys: ApiKeyRecord[] = [];

export const riskRules: RiskRules = {
  allowedTradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  allowedTradingSessionEnd: '23:59',
  allowedTradingSessionStart: '00:00',
  blockOrdersWithoutStop: true,
  botLossStreakPause: 3,
  cancelOnDisconnect: true,
  confirmLiveOrders: true,
  dailyLossLimit: 3,
  emergencyKillSwitch: false,
  maxLeverage: 5,
  maxRiskPerTrade: 1,
  minimumBalance: 1000,
  stopBotsAtDrawdown: 8,
  weeklyLossLimit: 7,
};

export const tradeLimits: TradeLimits = {
  cooldownAfterBotErrorMinutes: 20,
  cooldownAfterLossMinutes: 15,
  marketLimits: [
    { exposure: 12000, maxSize: 9000, symbol: 'BTC/USDT' },
    { exposure: 9000, maxSize: 6500, symbol: 'ETH/USDT' },
    { exposure: 4500, maxSize: 3200, symbol: 'SOL/USDT' },
  ],
  maxApiErrorsBeforePause: 3,
  maxBotSlotsActive: 4,
  maxOpenPositions: 3,
  maxOrdersPerDay: 18,
  maxOrdersPerHour: 6,
  maxPositionSizePerPair: 12500,
  maxStrategyExecutionsPerDay: 40,
  maxTotalExposure: 25000,
};

export const auditLogs: AuditEvent[] = [];

export const userProfile: UserProfile = {
  country: 'FR',
  email: 'artisaul@example.invalid',
  id: 'user-artisaul',
  language: 'fr',
  mainCurrency: 'USDT',
  name: 'Artisaul',
  timezone: 'Europe/Paris',
  tradingExperience: 'intermediate',
  username: 'artisaul',
};

export const userPreferences: UserPreferences = {
  accent: 'blue',
  analyticsConsent: true,
  billingSettings: {
    billingPeriod: 'yearly',
    localReceipts: [],
    nextRenewalAt: '2026-06-17T00:00:00.000Z',
    planId: 'pro',
    status: 'active',
    updatedAt: new Date(0).toISOString(),
  },
  breakEvenAutomation: true,
  breakEvenRule: 'move-to-be-at-1r',
  categoryFilters: ['all', 'trending', 'defi', 'layer-1'],
  defaultAccount: 'Main Account',
  defaultExchange: 'Paper',
  defaultLeverage: 3,
  defaultRiskPerTrade: 1,
  defaultSlippage: 0.5,
  density: 'compact',
  keyboardShortcuts: {
    enabled: true,
    shortcuts: [
      { action: 'Charts', category: 'Navigation', id: 'nav-charts', key: 'C', scope: 'App' },
      { action: 'Watchlist', category: 'Navigation', id: 'nav-watchlist', key: 'W', scope: 'App' },
      { action: 'Backtest', category: 'Navigation', id: 'nav-backtest', key: 'B', scope: 'App' },
      { action: 'Strategies', category: 'Navigation', id: 'nav-strategies', key: 'S', scope: 'App' },
      { action: 'Indicators', category: 'Chart', id: 'chart-indicators', key: 'I', scope: 'Chart' },
      { action: 'Draw tool', category: 'Chart', id: 'chart-draw', key: 'D', scope: 'Chart' },
      { action: 'Save Setup', category: 'Chart', id: 'chart-save-setup', key: 'Ctrl/Cmd + S', scope: 'Chart' },
      { action: 'Entry marker', category: 'Trade Markers', id: 'marker-entry', key: 'Alt + E', scope: 'Chart' },
      { action: 'Exit marker', category: 'Trade Markers', id: 'marker-exit', key: 'Alt + X', scope: 'Chart' },
      { action: 'Stop Loss marker', category: 'Trade Markers', id: 'marker-stop-loss', key: 'Alt + L', scope: 'Chart' },
      { action: 'Take Profit marker', category: 'Trade Markers', id: 'marker-take-profit', key: 'Alt + T', scope: 'Chart' },
      { action: 'Orders', category: 'Orders', id: 'orders-open', key: 'O', scope: 'App' },
      { action: 'Close dialog', category: 'Orders', id: 'orders-close-dialog', key: 'Esc', scope: 'Modal' },
      { action: 'Confirm modal', category: 'Orders', id: 'orders-confirm-modal', key: 'Ctrl/Cmd + Enter', safety: 'confirm', scope: 'Modal' },
      { action: 'Pause bot', category: 'Bots', id: 'bots-pause', key: 'P', safety: 'confirm', scope: 'Bots' },
      { action: 'Bot logs', category: 'Bots', id: 'bots-logs', key: 'G', scope: 'Bots' },
      { action: 'Run backtest', category: 'Backtest', id: 'backtest-run', key: 'R', scope: 'Backtest' },
      { action: 'Replay play/pause', category: 'Backtest', id: 'backtest-replay', key: 'Space', scope: 'Replay' },
    ],
    updatedAt: new Date(0).toISOString(),
  },
  multiTpBehavior: 'partial-take-profits',
  orderType: 'limit',
  personalizedExperience: true,
  positionSizingMethod: 'risk-percent',
  preferredMarketType: 'perpetual',
  quickPreset: 'day-trading',
  stopLossMode: 'sl-market',
  takeProfitMode: 'tp-limit',
  theme: 'dark',
  trailingStopActivationAtr: 1,
  trailingStopEnabled: true,
  trailingStopTrailAtr: 1.5,
  workspaceLayouts: {
    activeLayoutId: 'single-chart',
    defaultLayoutId: 'single-chart',
    layouts: [
      {
        default: true,
        id: 'single-chart',
        kind: 'single',
        name: 'Single Chart',
        panels: 'Chart + orders',
        settings: { alertsPanel: false, bottomPanel: true, newsFeed: false, orderPanel: true, primaryChart: true, rightPanel: true, watchlist: true },
        updatedAt: new Date(0).toISOString(),
      },
      {
        id: 'multi-chart',
        kind: 'multi',
        name: 'Multi-Chart',
        panels: '2 charts + watchlist',
        settings: { alertsPanel: true, bottomPanel: false, newsFeed: false, orderPanel: false, primaryChart: true, rightPanel: true, watchlist: true },
        updatedAt: new Date(0).toISOString(),
      },
      {
        id: 'bot-monitor',
        kind: 'bot',
        name: 'Bot Monitor',
        panels: 'Bots + logs',
        settings: { alertsPanel: true, bottomPanel: true, newsFeed: false, orderPanel: true, primaryChart: false, rightPanel: true, watchlist: false },
        updatedAt: new Date(0).toISOString(),
      },
      {
        id: 'backtest-lab',
        kind: 'backtest',
        name: 'Backtest Lab',
        panels: 'Inputs + report',
        settings: { alertsPanel: false, bottomPanel: true, newsFeed: false, orderPanel: false, primaryChart: true, rightPanel: false, watchlist: false },
        updatedAt: new Date(0).toISOString(),
      },
      {
        id: 'trade-journal',
        kind: 'journal',
        name: 'Trade Journal',
        panels: 'Journal + detail',
        settings: { alertsPanel: false, bottomPanel: true, newsFeed: false, orderPanel: false, primaryChart: false, rightPanel: true, watchlist: true },
        updatedAt: new Date(0).toISOString(),
      },
    ],
    panelDocking: 'right',
    sidebarBehavior: 'expanded',
    updatedAt: new Date(0).toISOString(),
  },
};
