import type { AgentSettings } from '../types/trading';

export const defaultAgentSettings: AgentSettings = {
  askBefore: {
    archive_variant: true,
    create_draft_bot: true,
    create_variant: false,
    prepare_bot: true,
    promote_version: true,
    run_backtest: false,
    run_paper_test: false,
    send_to_paper: false,
  },
  enabled: true,
  instructions: {
    allowedMarkets: 'Dynamic live Binance USDT universe. Start with current top liquid pairs, target 100 pairs as live data permits.',
    allowedParameters:
      'Only explicit engine inputs: TRIX length/signal, MA type/lengths, Donchian length, RSI levels, ATR stop/trail multipliers, drawdown/drawup lookbacks and recovery thresholds, risk percent.',
    archiveRules: 'Archive weak variants only. Protected source strategies are never archived or replaced.',
    forbiddenParameters: 'API keys, live trading, withdrawal permissions, trade limits, leverage increase, stop-loss removal, editing protected source strategies.',
    general:
      'The agent may research public TradingView metadata, create separate strategy variants, and run strict live-candle backtests. It must never fabricate performance, fill missing candles, use synthetic data, or present simulated paper results as real. If a provider is unavailable, mark the run failed or blocked instead of guessing.',
    mainStrategy: 'Protected core strategies stay unchanged; generated variants and TradingView adaptations remain separate records.',
    paperTestingRules: 'Paper testing is required before any bot is considered live-ready. Paper performance is recorded only from actual paper trades.',
    promotionRules: 'Explore broadly in backtest. Promote only after enough trades, acceptable drawdown, clean audit trail, and no critical warnings.',
    reportStyle: 'Short summary first, evidence and blockers visible.',
    validationRules:
      'For each strategy, test multiple cryptos and timeframes from the live top-100 USDT universe. Rotate batches so a single crypto cannot monopolize the cron. If no new TradingView strategy is found, create or innovate a separate agent strategy and test it. Rank candidates by bot score, net profit, profit factor, max drawdown, sample size, winrate rule, buy-and-hold comparison, data source, candle checksum and paper behavior. Only suggest bot use when the result is profitable and either winrate is at least 80% or winrate is below 50% with positive expectancy. If evidence is missing, say missing. Never optimize reports to satisfy the requested threshold; report the truth.',
  },
  limits: {
    allowedMarkets: [],
    allowedTimeframes: ['5m', '15m', '30m', '1h', '2h', '4h'],
    maxBacktestsPerDay: 500,
    maxDrawdownCandidate: 10,
    maxVariantsPerDay: 100,
    minPaperDays: 14,
    minProfitFactor: 1.2,
    minTrades: 30,
    paperRequiredBeforeLive: true,
  },
  mode: 'limited_autonomous',
  neverWithoutConfirmation: {
    archive_variant: true,
    execute_live_trade: true,
    launch_live_bot: true,
    promote_version: true,
  },
  permissions: {
    analyze_strategy: true,
    archive_variant: true,
    close_positions: false,
    create_draft_bot: true,
    create_report: true,
    create_variant: true,
    delete_strategy: false,
    edit_original_strategy: false,
    edit_variant: true,
    execute_live_trade: false,
    launch_live_bot: false,
    modify_api_keys: false,
    modify_risk_rules: false,
    modify_trade_limits: false,
    prepare_bot: true,
    promote_version: true,
    read_audit_logs: true,
    read_journal: true,
    revoke_api_key: false,
    run_backtest: true,
    run_paper_test: true,
    suggest_risk_change: true,
    write_journal_note: true,
  },
  policies: {
    analyze_strategy: 'auto_allowed',
    archive_variant: 'always_confirm',
    create_draft_bot: 'ask_first',
    create_report: 'auto_allowed',
    create_variant: 'auto_allowed',
    execute_live_trade: 'forbidden',
    launch_live_bot: 'forbidden',
    prepare_bot: 'ask_first',
    promote_version: 'always_confirm',
    run_backtest: 'auto_allowed',
    run_paper_test: 'auto_allowed',
    send_to_paper: 'auto_allowed',
  },
  queuePaused: false,
};
